apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: appmon
spec:
  expose: true
  route:
    termination: reencrypt
    path: '/resorts'
    host: 'modresort.apps-crc.testing'
  applicationImage: quay.io/jmanning/ol-demo-app:latest
  pullPolicy: Always
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: appmod-svc-tls
    certificateSecretRef: appmod-svc-tls
    port: 9443
