apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: appmod
spec:
  applicationImage: quay.io/jmanning/ol-demo-app:latest
  pullPolicy: Always
  expose: true
  route:
    host: 'modresort.apps-crc.testing'
    path: '/resorts'
